### ISSUE TITLE
New Feature Request: Add Sponsorship Information just like intern repo

### ISSUE THREAD

**Issue by sud298** [coderQuad/New-Grad-Positions-2023#652]
### Improvement

Please add the sponsorship information just like 2024 summer internship repository.

**Comment by cwcoogan** [comment]
Hi, thanks for you input. This repository includes sponsorship information. When submitting a new grad position, we ask that the community properly labels each position. If you are finding some incorrectly labeled, please submit an edit position issue correctly fixing this. Thank you.
