### ISSUE TITLE
New Role

### ISSUE THREAD

**Issue by zmartinezperpay** [coderQuad/New-Grad-Positions-2023#653]
### Link to Job Posting

https://boards.greenhouse.io/perpay/jobs/4034489007

### Company Name

Perpay

### Job Title

Junior Data Analyst

### Location

Philadelphia, Pa

### Does this job offer sponsorship?

Offers Sponsorship

### Is this internship currently accepting applications?

Yes

### Email associated with your GitHub account (Optional)

zachary.martinez@perpay.com

### Extra Notes (Optional)

Would love to share this great job with you all! sql, python, domo (business intelligence) stack. If this doesn't meet your requirements for posting, please reach out! zachary.martinez@perpay.com

**Comment by cwcoogan** [comment]
Hi Zach. Thanks for contributing! We are happy to see job postings from Perpay in both the repositories (2024 summer internship and the new grad).
