### ISSUE TITLE
New Role

### ISSUE THREAD

**Issue by lizebear** [coderQuad/New-Grad-Positions-2023#669]
### Link to Job Posting

https://boards.greenhouse.io/8451university/jobs/6864978002

### Company Name

84.51°

### Job Title

Data Scientist

### Location

Chicago, IL | Cincinnati, OH

### Does this job offer sponsorship?

Does Not Offer Sponsorship

### Is this internship currently accepting applications?

Yes

### Extra Notes (Optional)

This is the Data Science/Tech arm of Kroger - 2nd largest grocer in the US behind Walmart

**Comment by cwcoogan** [comment]
This looks like an internship style program (12 week duration total).

**Comment by lizebear** [comment]
I think it's still a full time role though after the program with the development part being 12 weeks - took this from their website - "If you are getting ready to graduate or early in your career and looking to change career paths, we offer full-time positions with space to learn on the job. Our development programs support, develop and accelerate entry-level talent in Data Science, Product and Design, Consulting, Engineering and Consumer Research."
