### ISSUE TITLE
Client Solutions Engineer at Cover Genius

### ISSUE THREAD

**Issue by 0zz10** [coderQuad/New-Grad-Positions-2023#699]
### Link to Job Posting

https://jobs.lever.co/covergenius/72479b81-b9f2-4d21-87d9-8d6c7d87c22b/

### Company Name

Cover Genius

### Job Title

Client Solutions Engineer

### Location

NEW YORK | REMOTE

### Does this job offer sponsorship?

Offers Sponsorship

### Is this internship currently accepting applications?

No

### Email associated with your GitHub account (Optional)

zzjdan@gmail.com

**Comment by jionkim00** [comment]
Hello, I don't think this is a New Grad role.
