### ISSUE TITLE
New Role

### ISSUE THREAD

**Issue by Sakalak6** [coderQuad/New-Grad-Positions-2023#701]
### Link to Job Posting

https://careers.morningstar.com/us/en/job/REQ-040918/Morningstar-Development-Program-for-Technologists

### Company Name

Morningstar

### Job Title

MDP Software Engineer

### Location

Chicago, IL

### Does this job offer sponsorship?

Offers Sponsorship

### Is this internship currently accepting applications?

Yes

**Comment by vanshb03** [comment]
Not open anymore @Sakalak6
