### ISSUE TITLE
Software Engineer

### ISSUE THREAD

**Issue by cathy-solopulseco** [coderQuad/New-Grad-Positions-2023#710]
### Link to Job Posting

https://jobs.lever.co/solopulseco/b2eb60f7-7281-4b12-9fdb-44d377b3e0dd

### Company Name

SoloPulse

### Job Title

Software Engineer

### Location

Atlanta, GA

### Does this job offer sponsorship?

U.S. Citizenship is Required

### Is this internship currently accepting applications?

Yes

### Email associated with your GitHub account (Optional)

cathy@solopulseco.com

### Extra Notes (Optional)

SoloPulse Corp is a dual-use radar company committed to the relentless exploration of the frontiers of radar sensing technology. Through the utilization of novel advanced wave theory algorithms, underpinned by the principles of special relativity, SoloPulse can achieve state of the art resolution and latency metrics. Located in Atlanta, GA, SoloPulse stands as a venture-backed startup, diligently cultivating strategic collaborations to proactively address critical safety imperatives and emerging autonomy needs across both civilian and military domains. Our distinguished team encompasses accomplished engineers, seasoned advisors, and experienced startup veterans, collectively driven by an overarching mission to change the way the world sees. 

As a Software Engineer at SoloPulse, you will play a critical role in the development of our software solutions. You will work on a wide range of tasks, from algorithm development to frontend-backend integration. This role requires expertise in Python, C++ and JavaScript, as well as a strong background in algorithm development. At SoloPulse, you will have the opportunity to work in a fast-paced, autonomous, and innovative environment that values independent thinking and initiative.

**Comment by rushilsrivastava** [comment]
Hey Cathy! In order to maintain quality of the repository, we are only listing verified companies. Feel free to reach out [here](https://simplify.jobs/employers) if you are looking for help recruiting!
