### ISSUE TITLE
Request for Community Maintainers

### ISSUE THREAD

**Issue by yan-michael** [coderQuad/New-Grad-Positions-2023#711]
### Issue/Question

We're looking to add a few other maintainers from the community to help us maintain this list. If you are interested, please comment below and we'll set you up!

**Comment by GbotemiB** [comment]
Hi @yan-michael, I would love to help out. I am currently a new grad looking for opportunities. I think i can use this medium to contribute back to the community.

**Comment by PratikThoratNortheastern** [comment]
Hi Micheal, Please let me know how I can help. I am a new grad looking for jobs using this repository so I would be grateful to give back to the community.

**Comment by nelson123-lab** [comment]
Hey @yan-michael I am interested. I am a 2024 New grad using this repository.

**Comment by renweview** [comment]
Interested! @yan-michael
