### ISSUE TITLE
New Role

### ISSUE THREAD

**Issue by richardwu** [coderQuad/New-Grad-Positions-2023#724]
### Link to Job Posting

links.tensor.trade/s/fullstack

### Company Name

Tensor Labs Inc.

### Job Title

Full-Stack Software Engineer

### Location

Toronto, Canada | Remote

### Does this job offer sponsorship?

Only in Canada

### Is this internship currently accepting applications?

Yes

### Email associated with your GitHub account (Optional)

richard@tensor.so

**Comment by rushilsrivastava** [comment]
Hey Richard! In order to maintain quality of the repository, we are only listing verified companies. Feel free to reach out [here](https://simplify.jobs/employers) if you are looking for help recruiting!
