### ISSUE TITLE
Scale AI/RemoTasks (QA Engineering Positon $55/hr)

### ISSUE THREAD

**Issue by ajkraus04** [coderQuad/New-Grad-Positions-2023#725]
### Link to Job Posting

https://forms.gle/HZxgFbKeg4qk2vEH6

### Company Name

Scale AI/RemoTasks

### Job Title

QA Engineer

### Location

Remote

### Does this job offer sponsorship?

U.S. Citizenship is Required

### Is this internship currently accepting applications?

Yes

### Extra Notes (Optional)

I am from OKLabs a consulting company that is working with Scale AI to rapidly scale their QA Engineering Teams. They are currently looking to onboard around 100 engineers a week. This is a contract role where they pay is $55/hr for doing various tasks within the RLHF space.

Example projects might include:

- Evaluating the quality of AI-generated code, including human-readable summaries of your rationale
- Solve coding problems, writing functional and efficient code
- Writing robust test cases to confirm code works efficiently and effectively

In my honest opinion, this is the perfect role for New Grads or Engineers actively looking for full time SWE positions. Engineers are paid really well, but also get to choose their own hours and can continue their job searches.

If you have any questions, feel free to contact me:

Andrew Kraus
andrew@oklabs.io
201-364-2550

**Comment by vennala-sai** [comment]
Is this posting eligible for Canadian Citizens? we can acquire a TN Visa
with the offer letter.

**Comment by ajkraus04** [comment]
> a TN Visa

Unfortunately not!

**Comment by ajkraus04** [comment]
Unfortunately not at this moment.

**Comment by vennala-sai** [comment]
Ok, thanks for the reply.

**Comment by rushilsrivastava** [comment]
Hi AJ, at the moment, this repo is for verified postings direct from employers or from Simplify. Feel free to reach out to [here](https://simplify.jobs/employers) if you are looking for talent

**Comment by chigurusameeksha** [comment]
Hello, I'm Sameeksha Chiguru, I’m eager to connect and discuss this amazing opportunity. With a solid mix of research and industry experience in building cutting-edge data science solutions and solving complex data analytics problems to drive organizational growth, I strongly believe that I can make the right impact. Thanks!
