### ISSUE TITLE
New Feature Request

### ISSUE THREAD

**Issue by alexnicholsamu** [coderQuad/New-Grad-Positions-2023#770]
### Improvement

New Grad Repo for 2025? A few Quant/AI firms are already open, so it would be nice to have a repo for that

**Comment by rushilsrivastava** [comment]
We're converting this repo at the end of May!

**Comment by MaxObes** [comment]
Any update on this?

**Comment by yan-michael** [comment]
It's here!!! Please help by contributing roles!
