### ISSUE TITLE
Editing Role

### ISSUE THREAD

**Issue by evanhu1** [coderQuad/New-Grad-Positions-2023#772]
### Link to Job Posting

https://www.ycombinator.com/companies/shortbread/jobs/8jV0RY9-founding-engineer

### Company Name

Shortbread

### Job Title

Founding Full Stack Engineer

### Location

San Francisco, CA

### Does this job offer sponsorship?
We sponsor OPT for visa

### Is this job posting currently accepting applications?

Yes

### Remove this job from the list?

- [ ] Yes, remove this job

**Comment by rushilsrivastava** [comment]
Hey Evan! We're taking a different approach for startups to ensure this list remains a high quality resource for new grads. Before we list startups on lists, we like to do research and build a dedicated company page to ensure great companies can find great talent. Please reach out to us directly to see if we can help [here](https://simplify.jobs/employers).
