### ISSUE TITLE
New Role

### ISSUE THREAD

**Issue by mike-gee** [coderQuad/New-Grad-Positions-2023#774]
### Link to Job Posting

https://the-gatekeep-app.notion.site/AI-Software-Engineer-Fashion-App-Startup-New-Grad-Full-Time-b2c5a6eff5104236bc533b79136f5b8b?pvs=74

### Company Name

Gatekeep

### Job Title

AI Software Engineer - Fashion App (New Grad, Full-Time)

### Location

San Francisco, CA | New York, NY | Remote

### Does this job offer sponsorship?

Offers Sponsorship

### Is this internship currently accepting applications?

Yes

**Comment by rushilsrivastava** [comment]
Hey Mike! Thanks for contributing. Unfortunately, we were not able to find much information about this company. This repo is a sync of job postings from [Simplify](https://simplify.jobs/), and community contributions of larger companies. If you represent this company, feel free to reach out to us directly [here](https://simplify.jobs/employers)
