### ISSUE TITLE
New Role

### ISSUE THREAD

**Issue by mark-nguyen1** [coderQuad/New-Grad-Positions-2023#776]
### Link to Job Posting

https://jobs.lever.co/hadrian/3267af26-986c-44d5-9a7f-4d59ddb47fb7

### Company Name

Hadrian

### Job Title

Frontend Software Engineer (Flow Team)

### Location

Los Angeles

### Does this job offer sponsorship?

U.S. Citizenship is Required

### Is this internship currently accepting applications?

Yes

### Email associated with your GitHub account (Optional)

lolitmark3@gmail.com

**Comment by rushilsrivastava** [comment]
Hey! These roles don't seem to be targeted for New Grad
