### ISSUE TITLE
Misc Issue: New Grad role for 2025

### ISSUE THREAD

**Issue by lucasisasuperman** [coderQuad/New-Grad-Positions-2023#782]
### Issue/Question

Hi, I was wondering if you will post new grad roles for students that will graduate in 2025. The current new grad roles in simplify does not specify for what year of graduates are. Thank you!

**Comment by yan-michael** [comment]
We've started labeling them! Would love if you all could help by submitting edit issues for job postings to help label them! For example, adding the dates to the title like "Software Engineer – New Grad (2024)"
