### ISSUE TITLE
New Software Engineer Role at Citadel Securities

### ISSUE THREAD

**Issue by DhyeyMavani2003** [coderQuad/New-Grad-Positions-2023#796]
### Link to Job Posting

https://www.citadelsecurities.com/careers/details/software-engineer-2025-university-graduate-us-2/

### Company Name

Citadel Securities

### Job Title

Software Engineer – 2025 University Graduate (US)

### Location

Miami, FL | New York, NY

### Does this job offer sponsorship?

Offers Sponsorship

### Is this internship currently accepting applications?

Yes

### Email associated with your GitHub account (Optional)

ddmavani2003@gmail.com

**Comment by GoBhargavi** [comment]
unsubscribe
