### ISSUE TITLE
New Role at Citadel (Hedge Fund) for Software Engineering

### ISSUE THREAD

**Issue by DhyeyMavani2003** [coderQuad/New-Grad-Positions-2023#797]
### Link to Job Posting

https://www.citadel.com/careers/details/software-engineer-2025-university-graduate-us/

### Company Name

Citadel

### Job Title

Software Engineer – 2025 University Graduate (US)

### Location

Chicago, IL | Miami, FL | New York, NY

### Does this job offer sponsorship?

Offers Sponsorship

### Is this internship currently accepting applications?

Yes

### Email associated with your GitHub account (Optional)

ddmavani2003@gmail.com

### Extra Notes (Optional)

This is the hedge fund role, and I have made a separate submission for citadel securities which is the market making side

**Comment by anutosh491** [comment]
Hi @DhyeyMavani2003 , I am kinda confused. When they write "Software Engineer – 2025 University Graduate (US)" are they expecting US grads only to apply ?

EDIT 1: I guess offering sponsorship means that the above might not be the case and non US citizens can apply too

**Comment by DhyeyMavani2003** [comment]
@anutosh491 anyone can apply as long as you go to college in the USA. They will sponsor all the visa matters as per my experience!

**Comment by anutosh491** [comment]
So you say grads/students from India can't apply ?

**Comment by DhyeyMavani2003** [comment]
Sorry I am not exactly sure, but I don't think they would be eligible to apply in this role since most of the direct new grad applicants from india are expected to apply to hong kong / singapore offices. I hope this helps! That being said, there is no harm in applying because they might be able to internally route your application, where it is supposed to go!

**Comment by DhyeyMavani2003** [comment]
@BigTunaHalpert can we merge this in?
