### ISSUE TITLE
New Role

### ISSUE THREAD

**Issue by seanlewertow** [coderQuad/New-Grad-Positions-2023#799]
### Link to Job Posting

https://hiring.fyjump.com/details-page?recordId=rectB8WB7qnfd3YhO

### Company Name

T-Mobile

### Job Title

Software Engineer

### Location

Frisco, TX

### Does this job offer sponsorship?

Offers Sponsorship

### Is this internship currently accepting applications?

Yes

### Email associated with your GitHub account (Optional)

seanlewertow@gmail.com

**Comment by yan-michael** [comment]
Not a new grad role!
