### ISSUE TITLE
Misc Issue

### ISSUE THREAD

**Issue by spatel0203** [coderQuad/New-Grad-Positions-2023#808]
### Issue/Question

This repo is missing a lot of new grad opportunities that have been coming out, was wondering if we could get a broader scope of the new grad opportunities this repo checks for.

**Comment by HarryZ10** [comment]
New grad scrapes is harder because not all posting will include details if it's entry level or not.

**Comment by yan-michael** [comment]
You are welcome to help contribute opportunities!
