### ISSUE TITLE
Editing Role

### ISSUE THREAD

**Issue by yadhira-8062** [coderQuad/New-Grad-Positions-2023#809]
### Link to Job Posting

https://jobs.jobvite.com/careers/splunk-careers/jobs?error=404&nl=1

### Company Name

Splunk

### Job Title

Software Engineer - Early in Career - Frontend	

### Location

Colorado | North Carolina

### Does this job offer sponsorship?

None

### Is this job posting currently accepting applications?

No

### Remove this job from the list?

- [ ] Yes, remove this job

### Reason for edit

The job listing no longer exists.

**Comment by yan-michael** [comment]
This is not the correct link. Please fix it and I will approve!

**Comment by yan-michael** [comment]
@reddoy Can you fix this
