### ISSUE TITLE
New Role

### ISSUE THREAD

**Issue by Talen-520** [coderQuad/New-Grad-Positions-2023#814]
### Link to Job Posting

https://stripe.com/jobs/listing/software-engineer-link/6105047?gh_src=73vnei

### Company Name

Stripe

### Job Title

Software Engineer, Link

### Location

South San Francisco HQ | New York | Seattle

### Does this job offer sponsorship?

Does Not Offer Sponsorship

### Is this internship currently accepting applications?

Yes

### Email associated with your GitHub account (Optional)

tao727188712@gmail.com

### Extra Notes (Optional)

This job does not indicate whether it offers sponsorship and does not have work experience requirement in the job description.

**Comment by yan-michael** [comment]
Thanks for contributing! Are you sure this is a new grad position?

**Comment by Talen-520** [comment]
> Thanks for contributing! Are you sure this is a new grad position?

This role does not specify that it is new grad position, at the same time, there is no mandatory requirement for working experience, so I think this job is qualified for new grad

**Comment by hemanthy1** [comment]
It seems the posting is now closed
