### ISSUE TITLE
New Feature Request

### ISSUE THREAD

**Issue by nerdanar** [coderQuad/New-Grad-Positions-2023#821]
### Improvement

Hello team,
this is a very good resource for the graduates to find jobs. Could you please add jobs in India to this?
As there are many indian students who are looking for jobs but don't have any such centralised source. It would be of great help for the student community.
Thanks

**Comment by rushilsrivastava** [comment]
Hey! Unfortunately, jobs in India are out of scope for this repository. We may consider adding a new repository in the future but don't have any plans to do so at the moment.
