### ISSUE TITLE
New Role

### ISSUE THREAD

**Issue by mwam-hackathon** [coderQuad/New-Grad-Positions-2023#827]
### Link to Job Posting

https://www.mwam.com/technology-graduate-scheme/

### Company Name

Marshall Wace

### Job Title

Software Engineer – New Grad

### Location

London | NYC | Singapore

### Does this job offer sponsorship?

Offers Sponsorship

### Is this internship currently accepting applications?

Yes

**Comment by reddoy** [comment]
Are you sure this is a software position? This seems more like a generalist role

**Comment by mwam-hackathon** [comment]
Yes! This is a software position. Every graduate rotation will utilize cs fundamentals and beyond. Some examples of rotations (not all encompassing) include market data ingestion, full stack development, big data extraction and optimization, etc.
