### ISSUE TITLE
Why is New grad roles not being updated consistently? Misc Issue

### ISSUE THREAD

**Issue by ajain02** [coderQuad/New-Grad-Positions-2023#832]
### Issue/Question

title. There are many open roles you guys are missing but the internship repo is up to date within hours

**Comment by 02danieljonas** [comment]
Thanks for the heads up, where are you finding the open roles?

**Comment by vanshb03** [comment]
Take a look at the other new grad repos that are up, the cvrve one has been pretty up to date.

**Comment by hemanthy1** [comment]
> ### Issue/Question
> title. There are many open roles you guys are missing but the internship repo is up to date within hours

Simply put, a majority of the roles posted on this repo are submitted by users like you. And the internship repo has over 3x as many stars as this repo, so it has many more people constantly watching and submitting new roles in that repo than this.
