### ISSUE TITLE
Quantitative Software Engineer

### ISSUE THREAD

**Issue by kanerai-recruiting** [coderQuad/New-Grad-Positions-2023#919]
### Link to Job Posting

https://www.kanerai.com/#careers

### Company Name

KANERAI

### Job Title

Software Engineer

### Location

Remote

### Does this job offer sponsorship?

Offers Sponsorship

### Is this job posting currently accepting applications?

None

### Permanently remove this job from the list?

- [ ] Yes, remove this job

### Email associated with your GitHub account (Optional)

recruiting-github@kanerai.com

### Reason for edit

**ABOUT THE JOB**

KANERAI is currently looking for candidates to join our Remote Research & Development Team. You’ll be responsible for small and large projects, both tactical and strategic, that directly impact our business. You will have the opportunity to contribute value across our entire stack: cloud computing, microservices, distributed computing, data management, advanced financial analytics, sophisticated data visualization and web applications. You will also be able to receive training on our stack as well as in financial analytics, work with talented team members, and provide input on our research and product development roadmaps.

**ABOUT YOU**

You love software. Whether you are a developer by training or just use programming in another field, you have always been more curious than your peers about how software works — legacy and modern programming languages, operating systems, distributed systems, open source frameworks, how concepts and implementations compare and contrast, and so on. You have been satisfying this curiosity, accumulating over time exceptional technical breadth and depth. You don’t want to stop. You want to be part of a team of like-minded learners and doers to build something unique and interesting that is changing the way that Wall Street looks at complex financial instruments.

**ABOUT US**

KANERAI was formed by a unique team of entrepreneurial and talented Wall Street traders, quants, technologists, and scientists who shared a passion for technology and the vision to empower investors with unprecedented insight into complex derivative instruments. Today, the largest and most sophisticated investors use KANERAI’s suite of trading and investment platforms. KANERAI prides itself on being a lean and efficient company of dedicated, hands-on and hardworking individuals who strive as a cohesive team to do much more with less.

To apply email us at [recruiting@kanerai.com](mailto:recruiting@kanerai.com).

**Comment by kanerai-recruiting** [comment]
Hi Rushil!

I tried to follow the instructions below and created this [issue](https://github.com/SimplifyJobs/New-Grad-Positions/issues/919):

> Adding a Job
Cool! You're ready to add a job to the list. Follow these steps:
First create a new issue [here](https://github.com/SimplifyJobs/New-Grad-Positions/issues/new/choose).
Select the New Role issue template.
Fill in the information about your job opening into the form, then hit submit.
Please make a new submission for each unique position, even if they are for the same company.
That's it! Once a member of our team has reviewed your submission, it will be automatically added to the README

But don't see my submission automatically added to the table in https://github.com/SimplifyJobs/New-Grad-Positions.
Anything else I need to do, please?

Thanks for your help!

José

**Comment by rushilsrivastava** [comment]
Hi José, in order to limit potential scam and unverified listings, we're not accepting postings from non-verified companies at this time. Happy to help you get setup on Simplify, feel free to schedule a call [here](https://simplify.jobs/employers).

**Comment by kanerai-recruiting** [comment]
Hi Rushil,

We have live openings now and would love to post on your site. However:

I used the link you provided ([here](https://simplify.jobs/employers)) to schedule a call. I tried three times. Last week, earlier this week, just now. After submitting the form, I get the message "Thanks so much for your interest! :)" and otherwise a blank page. I also don't see an email.

Could you help me, please?

Thanks

José
