### ISSUE TITLE
2025 Quant Research Summer Intern

### ISSUE THREAD

**Issue by muddy21** [coderQuad/New-Grad-Positions-2023#927]
### Link to Job Posting

https://job-boards.greenhouse.io/schonfeld/jobs/6250099?gh_src=e73f47fb1us

### Company Name

Schonfeld

### Job Title

2025 Quant Research Summer Intern

### Location

New York

### Does this job offer sponsorship?

Offers Sponsorship

### Is this internship currently accepting applications?

Yes

**Comment by yan-michael** [comment]
This is not a new grad role
