### ISSUE TITLE
Technology Leadership Program – Risk & Security Engineering

### ISSUE THREAD

**Issue by shreeyapatell** [coderQuad/New-Grad-Positions-2023#928]
### Link to Job Posting

https://www.vanguardjobs.com/job/20800660/technology-leadership-program-risk-security-engineering-nc-charlotte-nc/?source=Corporate_Website

### Company Name

Vanguard

### Job Title

Technology Leadership Program

### Location

Charlotte, NC

### Does this job offer sponsorship?

Does Not Offer Sponsorship

### Is this internship currently accepting applications?

Yes

### Email associated with your GitHub account (Optional)

shreeyapaatel@gmail.com

**Comment by Tolu-Mals** [comment]
Website says "Vanguard is not offering sponsorship for this position"
