### ISSUE TITLE
Closed🔒roles still open on official website

### ISSUE THREAD

**Issue by daniel620** [coderQuad/New-Grad-Positions-2023#942]
### Issue/Question

Description:
I have observed that several roles, which are currently marked as ‘closed’ 🔒 in our internal table, are still listed as active on the companies’ official websites. This raises some questions about the accuracy and timeliness of our data updates.

Questions:

1. Does this discrepancy indicate that these roles have been re-opened by the companies after being marked as closed in our system?
2. Should I consider applying to these roles, or does the ‘closed’ status in our table mean that they are no longer accepting resumes, regardless of what is shown on the official website?

**Comment by Hossain2024** [comment]
I have the same question 😭

**Comment by yan-michael** [comment]
It means that the companies are re-opening the positions – you can create an "edit" ticket to mark them as re-opened. Companies often do this after going through a first pass of interviews and deciding to re-open for more inbound!
