### ISSUE TITLE
Client Partner | Bay Area, California | OPT | GC |US Citizen

### ISSUE THREAD

**Issue by recruiter-kal** [coderQuad/New-Grad-Positions-2023#943]
### Link to Job Posting

https://www.linkedin.com/posts/kdheiva_exciting-opportunity-for-fresh-graduates-activity-7233184259081912320-Dfa9?utm_source=share&utm_medium=member_desktop

### Company Name

Vibhathi Labs Inc

### Job Title

Client Partner

### Location

San Francisco, CA

### Does this job offer sponsorship?

Other

### Is this internship currently accepting applications?

Yes

### Email associated with your GitHub account (Optional)

kalai@vibhathi.com

**Comment by rushilsrivastava** [comment]
Staffing firm postings are not allowed on this repository.
